# Add names ---------------------------------------------------------------

#' Set names of a vector
#'
#' @param x Vector
#' @param names Character vector of names (or coercible to a character vector)
#' @returns Named version of input
#' @export
set_names <- function(x, names = x) {
  #names(x) <- rep_len(as.character(names), length(x))
  names(x) <- names
  x
}

# Information about names -------------------------------------------------

#' Determine whether all elements are named
#'
#' @param x List or vector
#' @returns Logical of length 1
#' @noRd
all_named <- function(x) {
  x_names <- names(x)
  if (is.null(x_names)) return(rep(FALSE, length(x)))
  all(!is.na(x_names) & nzchar(x_names))
}

# Helpers -----------------------------------------------------------------

#' Clean column names for data frame
#'
#' @param x Character vector of column names
#' @param prefix Prefix for names that begin with non-letter. Default is `"V"`
#' @param max_width Maximum number of characters in names. Default is `100`
#' @param unique If `TRUE` (default), names are made unique
#' @param lower If `TRUE`, output converted to lowercase. Default is `FALSE`
#' @returns Character vector containing names
#' @export
clean_names <- function(x, prefix = "V", max_width = 100L, unique = TRUE, lower = FALSE) {
  # Ensure names start with letter
  x <- sub("^[^A-Za-z\\.]+", paste0(prefix, "_"), x)

  # Replace ++ with _hi_
  x <- gsub("\\+\\++", "_hi_", x)

  # Replace + with _pos_
  x <- gsub("\\++", "_pos_", x)

  # Replace < with _less_than_
  x <- gsub("<+", "_more_than_", x)

  # Replace < with _more_than_
  x <- gsub(">+", "_more_than_", x)

  # Replace = with _equals_
  x <- gsub("=+", "_equals_", x)

  # Replace punctuation and spaces with _
  x <- gsub("[^A-Za-z0-9_\\s]", "_", x)

  # Replace multiple _ with single _
  x <- gsub("_+", "_", x)

  # Ensure names are present
  idx <- !nzchar(x)
  x[idx] <- paste0(prefix, seq_along(x[idx]))

  # Ensure width <= max_width
  x <- substr(x, 1, max_width)

  # Remove _ from end
  x <- gsub("_$", "", x)

  # Ensure names unique
  if (unique) {
    x <- make.unique(x, sep = "_")
  }
  if (lower) {
    x <- tolower(x)
  }
  x
}

#' Force an object to have names
#'
#' @param x Data frame, list, or vector
#' @param prefix Prefix for names. Enter as length 1 character vector. Default is `"v"`
#' @noRd
.force_names <- function(x, prefix = "V") {
  if (is.null(x_names <- names(x))) return(paste0(prefix, seq_along(x)))
  idx <- !nzchar(x_names)
  x_names[idx] <- paste0(prefix, seq_len(sum(idx)))
  x_names
}

#' Create unique name
#'
#' @param .new Proposed name. Enter as string
#' @param .old Existing names. Enter as character vector
#' @param .sep Separator to use for new names. New names are generated by appending `sep` followed by an integer to `.new`. The integer used will be the first (starting from 1) that doesn't result in a name that already exists in `.old`. Default is `"_"`
#' @noRd
.safe_name <- function(.new, .old, .sep = "_") {
  # .new must be after .old to ensure it doesn't take precedence over existing names
  z <- c(.old, .new)
  make.unique(z, sep = .sep)[length(z)]
}
